### ISSUE TITLE
v3. Definition lists, v3 lists

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/rfc2md#10]
* dl
* ul
* ol

**Comment by opoudjis** [comment]
By the way, @enlarsen: the first sublist in v2 XML file is no longer getting bullets. Please check.

**Comment by opoudjis** [comment]
@enlarsen  Let me know if you'd rather I do this, Erik. But I'd rather you do this. :)

**Comment by enlarsen** [comment]
I'm looking at it right now. Thanks.

**Comment by ronaldtse** [comment]
@enlarsen are we done with this? Trying to close done issues. Thanks!

**Comment by enlarsen** [comment]
Yes, it's done.
